development:
  adapter: mysql2
  encoding: utf8
  database: itronaut_dev
  pool: 5
  username: itronaut
  password: Sam3/led

test:
  adapter: mysql2
  encoding: utf8
  database: itronaut_dev
  pool: 5
  username: itronaut
  password: Sam3/led

production:
  adapter: mysql2
  encoding: utf8
  database: itronaut_dev
  pool: 5
  username: itronaut
  password: Sam3/led
